CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
)
CREATE TABLE articles(
  id SERIAL PRIMARY KEY,
  author_id INT NOT NULL UNIQUE,
  author_username VARCHAR(100) NOT NULL UNIQUE,
  

  
)